---- Sweet introduction
/* 
Welcome to the Smash-Brothers Broker Company! We are the leading broker for your car insurance!
We have a small database with our favourite customers and our prefered insurance provider.
You can see what fancy cars we have insured and what famous customers we have in our portfolio.
*/

---- clean-up for create new tables 
DROP TABLE car_colour;
DROP TABLE car_index;
DROP TABLE city;
DROP TABLE customer;
DROP TABLE insurance_package;
DROP TABLE owned_cars;

-- Generated by Oracle SQL Developer Data Modeler 21.4.2.059.0838
-- at: 2022-05-29 17:47:50 BST
-- site: Oracle Database 21c
-- type: Oracle Database 21c
-- predefined type, no DDL - MDSYS.SDO_GEOMETRY
-- predefined type, no DDL - XMLTYPE
CREATE TABLE car_colour (
colour_id INTEGER NOT NULL,
colour VARCHAR2(10) NOT NULL
);
ALTER TABLE car_colour ADD CONSTRAINT car_colour_pk PRIMARY KEY ( colour_id );
CREATE TABLE car_index (
car_id INTEGER NOT NULL,
brand VARCHAR2(50) NOT NULL,
model VARCHAR2(50) NOT NULL
);
ALTER TABLE car_index ADD CONSTRAINT car_index_pk PRIMARY KEY ( car_id );
CREATE TABLE city (
city_zip INTEGER NOT NULL,
city_name VARCHAR2(50) NOT NULL
);
ALTER TABLE city ADD CONSTRAINT city_pk PRIMARY KEY ( city_zip );
CREATE TABLE customer (
customer_id INTEGER NOT NULL,
first_name VARCHAR2(50) NOT NULL,
last_name VARCHAR2(50) NOT NULL,
zip_code INTEGER NOT NULL
);
ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( customer_id );
CREATE TABLE insurance_company (
company_id INTEGER NOT NULL,
company_name VARCHAR2(50) NOT NULL,
company_street VARCHAR2(50) NOT NULL,
zip_code INTEGER NOT NULL
);
ALTER TABLE insurance_company ADD CONSTRAINT insurance_company_pk PRIMARY KEY (
company_id );
CREATE TABLE insurance_package (
package_id INTEGER NOT NULL,
package_name VARCHAR2(50) NOT NULL,
package_cost FLOAT NOT NULL,
company_id INTEGER NOT NULL
);
ALTER TABLE insurance_package ADD CONSTRAINT insurance_package_pk PRIMARY KEY (
package_id );
CREATE TABLE owned_cars (
owned_car_id INTEGER NOT NULL,
milage INTEGER NOT NULL,
car_colour_id INTEGER NOT NULL,
package_id INTEGER NOT NULL,
customer_id INTEGER NOT NULL,
car_index_id INTEGER NOT NULL
);
CREATE UNIQUE INDEX owned_cars__idx ON
owned_cars (
car_index_id
ASC );
ALTER TABLE owned_cars ADD CONSTRAINT owned_cars_pk PRIMARY KEY ( owned_car_id
);
ALTER TABLE owned_cars
ADD CONSTRAINT car_colour_fk FOREIGN KEY ( car_colour_id )
REFERENCES car_colour ( colour_id );
ALTER TABLE owned_cars
ADD CONSTRAINT car_index_fk FOREIGN KEY ( car_index_id )
REFERENCES car_index ( car_id );
ALTER TABLE customer
ADD CONSTRAINT customer_city_fk FOREIGN KEY ( zip_code )
REFERENCES city ( city_zip );
ALTER TABLE owned_cars
ADD CONSTRAINT customer_id_fk FOREIGN KEY ( customer_id )
REFERENCES customer ( customer_id );
ALTER TABLE insurance_company
ADD CONSTRAINT insurance_company_city_fk FOREIGN KEY ( zip_code )
REFERENCES city ( city_zip );
ALTER TABLE insurance_package
ADD CONSTRAINT insurance_company_fk FOREIGN KEY ( company_id )
REFERENCES insurance_company ( company_id );
ALTER TABLE owned_cars
ADD CONSTRAINT insurance_package_fk FOREIGN KEY ( package_id )
REFERENCES insurance_package ( package_id );
